project:
  type: website

website:
  title: "Shigueru Nagata Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Aboud

format:
  html:
    theme:
      - cyborg
    css: styles.css
    toc: true


listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
